### ISSUE TITLE
Bjam bin missing from release/bin , causes make subAll to fail.

### ISSUE THREAD

**Issue by scbafk** [drmeister/legacy-externals-clasp#2]
Not sure if this is specific to my system setup but bjam bin was missing from externals/release/bin. This caused `make boost-build` to fail while running `make subAll`.

**Comment by drmeister** [comment]
Hello, thanks for the feedback!  Could you pull the latest commits of externals-clasp and clasp and try them again and tell me how it goes?   I've made a lot of fixes in the last couple of days.

**Comment by scbafk** [comment]
yeah sure, ill try it out later tonight.

**Comment by scbafk** [comment]
Build worked for both mps and boehm on OSX 10.9.4 , Xcode 6.0.1.

**Comment by drmeister** [comment]
Great!  I'll close out this issue then.  Drop in on IRC if you want to talk about where Clasp is going and maybe help out.

**Comment by rptb1** [comment]
@drmeister Where are you hanging out on IRC? No channel is mentioned in the README or announcement.

**Comment by drmeister** [comment]
On freenode, in #clasp
